"""Agregar columna hora a evento

Revision ID: 3cf08410deeb
Revises: d537df18e58f
Create Date: 2023-11-04 15:05:59.379549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf08410deeb'
down_revision: Union[str, None] = 'd537df18e58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('hora', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'hora')
    # ### end Alembic commands ###
