"""corrección en modelos habitos tarea

Revision ID: 7db95394cb2b
Revises: d5ed2c76d3b3
Create Date: 2023-10-28 09:06:33.406221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db95394cb2b'
down_revision: Union[str, None] = 'd5ed2c76d3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
