"""corrigiendo calendario

Revision ID: 96146a32a973
Revises: ae89a010943b
Create Date: 2023-09-09 11:29:24.759868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96146a32a973'
down_revision: Union[str, None] = 'ae89a010943b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendarios', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendarios', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendarios', type_='foreignkey')
    op.drop_column('calendarios', 'user_id')
    # ### end Alembic commands ###
