"""añadiendo calendario

Revision ID: ae89a010943b
Revises: 15dc10e1c935
Create Date: 2023-09-09 11:21:54.710686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae89a010943b'
down_revision: Union[str, None] = '15dc10e1c935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendarios_id'), 'calendarios', ['id'], unique=False)
    op.create_index(op.f('ix_calendarios_nombre'), 'calendarios', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendarios_nombre'), table_name='calendarios')
    op.drop_index(op.f('ix_calendarios_id'), table_name='calendarios')
    op.drop_table('calendarios')
    # ### end Alembic commands ###
