"""relacion entre eventos, habitos y calendario

Revision ID: d537df18e58f
Revises: 4ae170acf47b
Create Date: 2023-10-28 18:25:02.016814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd537df18e58f'
down_revision: Union[str, None] = '4ae170acf47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_evento', sa.String(), nullable=True),
    sa.Column('descripcion_evento', sa.String(), nullable=True),
    sa.Column('fecha_hora', sa.String(), nullable=True),
    sa.Column('id_habito', sa.Integer(), nullable=True),
    sa.Column('id_calendario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_calendario'], ['calendarios.id'], ),
    sa.ForeignKeyConstraint(['id_habito'], ['habitos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_id'), 'eventos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_id'), table_name='eventos')
    op.drop_table('eventos')
    # ### end Alembic commands ###
