"""Tareas en equipo

Revision ID: d5ed2c76d3b3
Revises: e3ea2c3793c9
Create Date: 2023-09-30 10:35:19.499488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ed2c76d3b3'
down_revision: Union[str, None] = 'e3ea2c3793c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
