"""Tareas en equipo

Revision ID: e3ea2c3793c9
Revises: f54c8fb97076
Create Date: 2023-09-30 09:19:46.237873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ea2c3793c9'
down_revision: Union[str, None] = 'f54c8fb97076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('regularidad', sa.Integer(), nullable=True),
    sa.Column('dias', sa.String(), nullable=True),
    sa.Column('dificultad', sa.String(), nullable=True),
    sa.Column('habitos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habitos_id'], ['habitos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_id'), 'tareas', ['id'], unique=False)
    op.create_index(op.f('ix_tareas_name'), 'tareas', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tareas_name'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_id'), table_name='tareas')
    op.drop_table('tareas')
    # ### end Alembic commands ###
